<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>gabrielacordova</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GabrielaCordova_files/libs/clipboard/clipboard.min.js"></script>
<script src="GabrielaCordova_files/libs/quarto-html/quarto.js"></script>
<script src="GabrielaCordova_files/libs/quarto-html/popper.min.js"></script>
<script src="GabrielaCordova_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GabrielaCordova_files/libs/quarto-html/anchor.min.js"></script>
<link href="GabrielaCordova_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GabrielaCordova_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GabrielaCordova_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GabrielaCordova_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GabrielaCordova_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">



<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Cargar los datos en un dataframe llamado: airbnb</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>airbnb<span class="ot">&lt;-</span><span class="fu">read.csv</span>(<span class="st">'data//airbnb.csv'</span>,<span class="at">sep =</span> <span class="st">','</span>, <span class="at">stringsAsFactors =</span> T)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p>Mostrar las primeras 6 filas del dataframe</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb, <span class="at">n =</span> <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Zipcode Neighbourhood.Cleansed Property.Type       Room.Type Accommodates
1   28004            Universidad     Apartment    Private room            2
2   28004            Universidad     Apartment Entire home/apt            6
3   28004            Universidad     Apartment Entire home/apt            3
4   28004            Universidad          Loft Entire home/apt            3
5   28015            Universidad     Apartment Entire home/apt            5
6   28004            Universidad     Apartment Entire home/apt            2
  Bathrooms Bedrooms Beds Bed.Type
1         2        1    1 Real Bed
2         1        3    5 Real Bed
3         1        2    2 Real Bed
4         2        1    1 Real Bed
5         1        1    1 Real Bed
6         1        0    1 Real Bed
                                                                                                                                                                                                                                                                                                                                                         Amenities
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  Square.Feet Price Review.Scores.Rating
1          NA    35                   NA
2          NA    92                   96
3          NA    55                   91
4          NA    60                  100
5         538    75                   90
6          NA    55                   95</code></pre>
</div>
</div>
<p>Renombrar las columnas de la siguiente forma:</p>
<table class="table">
<thead>
<tr class="header">
<th>Nombre original</th>
<th>Nuevo nombre</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Zipcode</td>
<td>CodigoPostal</td>
</tr>
<tr class="even">
<td>Neighbourhood.Cleansed</td>
<td>Barrio</td>
</tr>
<tr class="odd">
<td>Property.Type</td>
<td>TipoPropiedad</td>
</tr>
<tr class="even">
<td>Room.Type</td>
<td>TipoAlquiler</td>
</tr>
<tr class="odd">
<td>Accommodates</td>
<td>MaxOcupantes</td>
</tr>
<tr class="even">
<td>Bathrooms</td>
<td>NumBanyos</td>
</tr>
<tr class="odd">
<td>Bedrooms</td>
<td>NumDormitorios</td>
</tr>
<tr class="even">
<td>Beds</td>
<td>NumCamas</td>
</tr>
<tr class="odd">
<td>Bed.Type</td>
<td>TipoCama</td>
</tr>
<tr class="even">
<td>Amenities</td>
<td>Comodidades</td>
</tr>
<tr class="odd">
<td>Square.Feet</td>
<td>PiesCuadrados</td>
</tr>
<tr class="even">
<td>Price</td>
<td>Precio</td>
</tr>
<tr class="odd">
<td>Review.Scores.Rating</td>
<td>Puntuacion</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>newnames<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"CodigoPostal"</span>,<span class="st">"Barrio"</span>,<span class="st">"TipoPropiedad"</span>,<span class="st">"TipoAlquiler"</span>,<span class="st">"MaxOcupantes"</span>,<span class="st">"NumBanyos"</span>,</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="st">"NumDormitorios"</span>,<span class="st">"NumCamas"</span>,<span class="st">"TipoCama"</span>,<span class="st">"Comodidades"</span>,<span class="st">"PiesCuadrados"</span>,<span class="st">"Precio"</span>,<span class="st">"Puntuacion"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb) <span class="ot">&lt;-</span> newnames <span class="co">#nombre en espqanol de las columnas</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(airbnb) <span class="co">#comprobacion de las nuevos nombres de las columnas</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion
1            NA     35         NA
2            NA     92         96
3            NA     55         91
4            NA     60        100
5           538     75         90
6            NA     55         95</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "CodigoPostal"   "Barrio"         "TipoPropiedad"  "TipoAlquiler"  
 [5] "MaxOcupantes"   "NumBanyos"      "NumDormitorios" "NumCamas"      
 [9] "TipoCama"       "Comodidades"    "PiesCuadrados"  "Precio"        
[13] "Puntuacion"    </code></pre>
</div>
</div>
<p>Crea una nueva columna llamada MetrosCuadrados a partir de la columna PiesCuadrados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># El dataset inicial es "airbnb" pero voy a hacer modificaciones iniciales asi que me copio en uno llamado "df"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> airbnb</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># La nueva columna"MetrosCuadrados" se inicia con NA </span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> <span class="cn">NA</span> </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ver las columnas</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "CodigoPostal"    "Barrio"          "TipoPropiedad"   "TipoAlquiler"   
 [5] "MaxOcupantes"    "NumBanyos"       "NumDormitorios"  "NumCamas"       
 [9] "TipoCama"        "Comodidades"     "PiesCuadrados"   "Precio"         
[13] "Puntuacion"      "MetrosCuadrados"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df<span class="sc">$</span>PiesCuadrados, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  NA  NA  NA  NA 538</code></pre>
</div>
</div>
<p>Ayuda: 1 pie cuadrado son 0,092903 metros cuadrdados</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># cambiar la columna PiesCuadrados, usando la contante de la ayuda</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>MetrosCuadrados <span class="ot">&lt;-</span> df<span class="sc">$</span>PiesCuadrados <span class="sc">*</span> <span class="fl">0.092903</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># ver las columnas</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "CodigoPostal"    "Barrio"          "TipoPropiedad"   "TipoAlquiler"   
 [5] "MaxOcupantes"    "NumBanyos"       "NumDormitorios"  "NumCamas"       
 [9] "TipoCama"        "Comodidades"     "PiesCuadrados"   "Precio"         
[13] "Puntuacion"      "MetrosCuadrados"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df<span class="sc">$</span>MetrosCuadrados, <span class="at">n =</span> <span class="dv">5</span>) <span class="co"># tengo que tener NA y 538*0.092903 </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]       NA       NA       NA       NA 49.98181</code></pre>
</div>
</div>
<p>Miremos el código postal. Es una variable con entradas erroneas. Hay valores como ’‘,’-’ y ‘28’ que <strong>deberían ser considerados como NA</strong>. Así mismo también debería ser NA todos los que no compiencen por 28, ya que estamos con códigos postales de Madrid <strong>notebook1</strong></p>
<p>El código postal 28002, 28004 y 28051 tienen entradas repetidas. Por ejemplo las entradas 28002 deberían ir detro de 28002</p>
<p>El codigo 2804 debería ser 28004, 2805 deberia ser 28005 y 2815 juncto con 2815 debería ser 28015</p>
<p>Limpia los datos de la columna Codigo Postal</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reemplaza los valores vacíos, '-', y valores que no comienzan con '28' por NA</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">''</span> <span class="sc">|</span> df<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'-'</span> <span class="sc">|</span> <span class="sc">!</span><span class="fu">grepl</span>(<span class="st">"^28"</span>, df<span class="sc">$</span>CodigoPostal)] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Corrige códigos postales específicos</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co">#df$CodigoPostal &lt;- gsub("^2804$", "28004", df$CodigoPostal)</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co">#df$CodigoPostal &lt;- gsub("^2805$", "28005", df$CodigoPostal)</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co">#df$CodigoPostal &lt;- gsub("^2815$", "28015", df$CodigoPostal)</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir códigos postales con '\n' y mantener solo el primero</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co">#df$CodigoPostal &lt;- gsub("\n.*", "", df$CodigoPostal)</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'28002</span><span class="sc">\n</span><span class="st">28002'</span>]<span class="ot">&lt;-</span><span class="st">'28002'</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'28051</span><span class="sc">\n</span><span class="st">28051'</span>]<span class="ot">&lt;-</span><span class="st">'28051'</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'Madrid 28004'</span>]<span class="ot">&lt;-</span><span class="st">'28004'</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'2804'</span>]<span class="ot">&lt;-</span><span class="st">'28004'</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'2805'</span>]<span class="ot">&lt;-</span><span class="st">'28005'</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'2815'</span>]<span class="ot">&lt;-</span><span class="st">'28015'</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal[df<span class="sc">$</span>CodigoPostal<span class="sc">==</span><span class="st">'2015'</span>]<span class="ot">&lt;-</span><span class="st">'28015'</span></span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">gsub</span>(<span class="st">'[^(28)]</span><span class="sc">\\</span><span class="st">d{3}'</span>, <span class="cn">NA</span>, df<span class="sc">$</span>CodigoPostal)</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Convierte la columna "CodigoPostal" en factor para representar las categorías limpias</span></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>CodigoPostal <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>CodigoPostal)</span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-25"><a href="#cb19-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualiza las primeras filas del dataframe para verificar los cambios</span></span>
<span id="cb19-26"><a href="#cb19-26" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  CodigoPostal      Barrio TipoPropiedad    TipoAlquiler MaxOcupantes NumBanyos
1        28004 Universidad     Apartment    Private room            2         2
2        28004 Universidad     Apartment Entire home/apt            6         1
3        28004 Universidad     Apartment Entire home/apt            3         1
4        28004 Universidad          Loft Entire home/apt            3         2
5        28015 Universidad     Apartment Entire home/apt            5         1
6        28004 Universidad     Apartment Entire home/apt            2         1
  NumDormitorios NumCamas TipoCama
1              1        1 Real Bed
2              3        5 Real Bed
3              2        2 Real Bed
4              1        1 Real Bed
5              1        1 Real Bed
6              0        1 Real Bed
                                                                                                                                                                                                                                                                                                                                                       Comodidades
1                                                                                                                                                                              TV,Wireless Internet,Kitchen,Pets allowed,Pets live on this property,Buzzer/wireless intercom,Heating,Suitable for events,Washer,First aid kit,Essentials,Lock on bedroom door,Iron
2                                                                                                                                                                                      TV,Internet,Wireless Internet,Air conditioning,Kitchen,Indoor fireplace,Heating,Family/kid friendly,Washer,Dryer,Smoke detector,Carbon monoxide detector,Essentials,Shampoo
3                                                                                                                                                                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Doorman,Heating,Family/kid friendly,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace
4                                           TV,Internet,Wireless Internet,Air conditioning,Kitchen,Pets allowed,Breakfast,Elevator in building,Indoor fireplace,Buzzer/wireless intercom,Heating,Washer,Essentials,Shampoo,Hangers,Hair dryer,Iron,Laptop friendly workspace,translation missing: en.hosting_amenity_49,translation missing: en.hosting_amenity_50
5                                                                                                                                                                                                               TV,Wireless Internet,Air conditioning,Kitchen,Smoking allowed,Pets allowed,Elevator in building,Heating,Family/kid friendly,Washer,Essentials,Iron
6 TV,Cable TV,Internet,Wireless Internet,Air conditioning,Wheelchair accessible,Kitchen,Doorman,Elevator in building,Buzzer/wireless intercom,Heating,Washer,Smoke detector,Carbon monoxide detector,First aid kit,Safety card,Fire extinguisher,Essentials,Shampoo,24-hour check-in,Hangers,Hair dryer,Iron,Laptop friendly workspace,Self Check-In,Doorman Entry
  PiesCuadrados Precio Puntuacion MetrosCuadrados
1            NA     35         NA              NA
2            NA     92         96              NA
3            NA     55         91              NA
4            NA     60        100              NA
5           538     75         90        49.98181
6            NA     55         95              NA</code></pre>
</div>
</div>
<p>Una vez limpios los datos ¿Cuales son los códigos postales que tenemos?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">length</span>(<span class="fu">unique</span>(df<span class="sc">$</span>CodigoPostal)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 63</code></pre>
</div>
</div>
<p>¿Cuales son los 5 códigos postales con más entradas? ¿Y con menos? ¿Cuantas entradas tienen?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>codigopostal_counts <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">table</span>(df<span class="sc">$</span>CodigoPostal), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#¿Cuales son los 5 códigos postales con más entradas?</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(codigopostal_counts, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28012 28004 28005 28013 28014 
 2060  1795  1195  1019   630 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co">#¿Y con menos? </span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">tail</span>(codigopostal_counts, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
28058 28060 28094 28105 28850 
    1     1     1     1     1 </code></pre>
</div>
</div>
<p>¿Cuales son los barrios que hay en el código postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#filtro_cod_postal = df$CodigoPostal=="28012"</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(sum(na.omit(filtro_cod_postal)))</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>filtro_cod_postal <span class="ot">&lt;-</span> <span class="sc">!</span><span class="fu">is.na</span>(df<span class="sc">$</span>CodigoPostal) <span class="sc">&amp;</span> df<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">"28012"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#print((filtro_cod_postal))</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#print(unique(df$Barrio))</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>barrios <span class="ot">&lt;-</span> <span class="fu">unique</span>(df<span class="sc">$</span>Barrio[filtro_cod_postal])</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(barrios)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] Sol             Acacias         Palos de Moguer Embajadores    
 [5] Cortes          Palacio         Universidad     Delicias       
 [9] Arapiles        Atocha          Goya           
125 Levels: Abrantes Acacias Adelfas Aeropuerto Aguilas ... Zofío</code></pre>
</div>
</div>
<p>¿Cuantas entradas hay en cada uno de esos barrios para el codigo postal 28012?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar las entradas con código postal 28012</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>airbnb_28012 <span class="ot">&lt;-</span> df[df<span class="sc">$</span>CodigoPostal <span class="sc">==</span> <span class="st">'28012'</span>, ]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertir la columna "Barrio" en factor</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>airbnb_28012<span class="sc">$</span>Barrio <span class="ot">&lt;-</span> <span class="fu">factor</span>(airbnb_28012<span class="sc">$</span>Barrio)</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar las entradas en cada barrio para el código postal 28012</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>barrios_count <span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb_28012<span class="sc">$</span>Barrio)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el resultado</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>barrios_count</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        Acacias        Arapiles          Atocha          Cortes        Delicias 
             13               1               1             216               1 
    Embajadores            Goya         Palacio Palos de Moguer             Sol 
           1449               1              27              46             301 
    Universidad 
              4 </code></pre>
</div>
</div>
<p>¿Cuantos barrios hay en todo el dataset airbnb? ¿Cuales son?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># total unicos</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">length</span>(<span class="fu">unique</span>(df<span class="sc">$</span>Barrio)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 125</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># barrios</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(unique(df$Barrio))</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cuales son los 5 barrios que tienen mayor número entradas?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Barrio_counts <span class="ot">&lt;-</span> <span class="fu">sort</span>(<span class="fu">table</span>(df<span class="sc">$</span>Barrio), <span class="at">decreasing =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="co">#print(Barrio_counts)</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="co">#¿Cuales son los 5 códigos barrios con más entradas?</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(Barrio_counts, <span class="at">n =</span> <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol    Justicia 
       1844        1358        1083         940         785 </code></pre>
</div>
</div>
<p>¿Cuantos Tipos de Alquiler diferentes hay? ¿Cuales son? ¿Cuantas entradas en el dataframe hay por cada tipo?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>alq_counts <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>TipoAlquiler)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">length</span>(alq_counts))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(alq_counts)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Entire home/apt    Private room     Shared room 
           7903            5113             191 </code></pre>
</div>
</div>
<p>Muestra el diagrama de cajas del precio para cada uno de los diferentes Tipos de Alquiler</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># 3 variables con los datos de cada tipo</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>tipo_entire <span class="ot">&lt;-</span> df[df<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">"Entire home/apt"</span>,]</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>tipo_private <span class="ot">&lt;-</span> df[df<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">"Private room"</span>,]</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>tipo_compartido <span class="ot">&lt;-</span> df[df<span class="sc">$</span>TipoAlquiler <span class="sc">==</span> <span class="st">"Shared room"</span>,]</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="co">#print(tipo_entire)</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear diagrama de cajas para cada tipo de alquiler</span></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>t_1 <span class="ot">&lt;-</span><span class="fu">ggplot</span>(tipo_entire, <span class="fu">aes</span>(<span class="at">y =</span> Precio)) <span class="sc">+</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>   <span class="fu">ggtitle</span>(<span class="st">"Entire home/apt"</span>)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>t_2 <span class="ot">&lt;-</span><span class="fu">ggplot</span>(tipo_private, <span class="fu">aes</span>(<span class="at">y =</span> Precio)) <span class="sc">+</span></span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Private room"</span>)</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a>t_3 <span class="ot">&lt;-</span><span class="fu">ggplot</span>(tipo_compartido, <span class="fu">aes</span>(<span class="at">y =</span> Precio)) <span class="sc">+</span></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Shared room"</span>)</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(t_1, t_2,t_3, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="GabrielaCordova_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Cual es el precio medio de alquiler de cada uno, la diferencia que hay ¿es estadísticamente significativa? ¿Con que test lo comprobarías?</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una lista para almacenar los resultados de las pruebas de normalidad gausiana</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>normality_results <span class="ot">&lt;-</span> <span class="fu">list</span>()</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Iterar a través de los grupos únicos en df$TipoAlquiler</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (tipo <span class="cf">in</span> <span class="fu">levels</span>(df<span class="sc">$</span>TipoAlquiler)) {</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>  df1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, TipoAlquiler <span class="sc">==</span> tipo)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Comprobar el tamaño de la muestra</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  sample_size <span class="ot">&lt;-</span> <span class="fu">nrow</span>(df1)</span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (sample_size <span class="sc">&gt;=</span> <span class="dv">3</span> <span class="sc">&amp;&amp;</span> sample_size <span class="sc">&lt;=</span> <span class="dv">5000</span>) {</span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Comprobar la normalidad con el test de Shapiro-Wilk</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>    shapiro_test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df1<span class="sc">$</span>Precio)</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Verificar la normalidad</span></span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (shapiro_test<span class="sc">$</span>p.value <span class="sc">&gt;=</span> <span class="fl">0.05</span>) {</span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Si la distribución es normal, almacenar el resultado en la lista de resultados de normalidad</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a>      normality_results[[tipo]] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb43-19"><a href="#cb43-19" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Si la distribución no es normal, almacenar el resultado en la lista de resultados de normalidad</span></span>
<span id="cb43-20"><a href="#cb43-20" aria-hidden="true" tabindex="-1"></a>      normality_results[[tipo]] <span class="ot">&lt;-</span> <span class="cn">FALSE</span></span>
<span id="cb43-21"><a href="#cb43-21" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb43-22"><a href="#cb43-22" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb43-23"><a href="#cb43-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Grupo"</span>, tipo, <span class="st">"tiene un tamaño de muestra fuera del rango permitido. Se omite el análisis."</span>))</span>
<span id="cb43-24"><a href="#cb43-24" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb43-25"><a href="#cb43-25" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grupo Entire home/apt tiene un tamaño de muestra fuera del rango permitido. Se omite el análisis."
[1] "Grupo Private room tiene un tamaño de muestra fuera del rango permitido. Se omite el análisis."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Iterar nuevamente a través de los grupos únicos en df$TipoAlquiler</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (tipo <span class="cf">in</span> <span class="fu">levels</span>(df<span class="sc">$</span>TipoAlquiler)) {</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Verificar si el grupo cumple con el tamaño de muestra y normalidad</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="sc">!</span><span class="fu">is.null</span>(normality_results[[tipo]])) {</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (normality_results[[tipo]]) {</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>      df1 <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, TipoAlquiler <span class="sc">==</span> tipo)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Precio medio tipo"</span>, tipo, <span class="st">" = "</span>, <span class="fu">mean</span>(df1<span class="sc">$</span>Precio, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)))</span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>      sp <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df1<span class="sc">$</span>Precio)</span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">" - Test Shapiro p-valor = "</span>, sp<span class="sc">$</span>p.value))</span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>      <span class="co"># Realizar un test ANOVA ya que la distribución es normal</span></span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>      anova_result <span class="ot">&lt;-</span> <span class="fu">anova</span>(<span class="fu">lm</span>(Precio <span class="sc">~</span> TipoAlquiler, <span class="at">data =</span> df1))</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">" - Test ANOVA p-valor = "</span>, anova_result<span class="sc">$</span><span class="st">`</span><span class="at">Pr(&gt;F)</span><span class="st">`</span>[<span class="dv">1</span>]))</span>
<span id="cb45-14"><a href="#cb45-14" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb45-15"><a href="#cb45-15" aria-hidden="true" tabindex="-1"></a>      <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Grupo"</span>, tipo, <span class="st">"no sigue una distribución gaussiana. Se omite el análisis."</span>))</span>
<span id="cb45-16"><a href="#cb45-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb45-17"><a href="#cb45-17" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb45-18"><a href="#cb45-18" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Grupo Shared room no sigue una distribución gaussiana. Se omite el análisis."</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar un test de kruskal para comparar las medias</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>kt <span class="ot">&lt;-</span> <span class="fu">kruskal.test</span>(Precio <span class="sc">~</span> TipoAlquiler, df)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir el resultado del test de kruskal</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Las medias son estadísticamente diferentes ya que el p-valor es muy bajo. p-valor="</span>, kt<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Las medias son estadísticamente diferentes ya que el p-valor es muy bajo. p-valor= 0</code></pre>
</div>
</div>
<p>Filtra el dataframe cuyos tipo de alquiler sea <strong>‘Entire home/apt’</strong> y guardalo en un dataframe llamado <strong><em>airbnb_entire</em></strong>. Estas serán las entradas que tienen un alquiler del piso completo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>airbnb_entire <span class="ot">&lt;-</span> <span class="fu">subset</span>(df, TipoAlquiler <span class="sc">==</span> <span class="st">"Entire home/apt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor número de apartamentos enteros en alquiler? <strong>mas elementos</strong>Nota: Mirar solo en airbnb_entire. A partir de este punto y hasta que se diga lo contrario partiremos de airbnb_entire.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Usar la función table para contar las frecuencias de cada barrio</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>barrios_tab<span class="ot">&lt;-</span> <span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar las frecuencias en orden descendente y seleccionar los primeros 5</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">sort</span>(barrios_tab, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Embajadores Universidad     Palacio         Sol      Cortes 
       1228         984         769         701         574 </code></pre>
</div>
</div>
<p>¿Cuales son los 5 barrios que tienen un mayor precio medio de alquiler para apartamentos enteros (es decir, del dataframe airbnb_entire)? ¿Cual es su precio medio?</p>
<p>Ayuda: Usa la función aggregate <code>aggregate(.~colname,df,mean,na.rm=TRUE)</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>precio_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(. <span class="sc">~</span>Barrio, airbnb_entire[,<span class="fu">c</span>(<span class="st">"Precio"</span>,<span class="st">"Barrio"</span>)], <span class="at">FUN =</span>mean, <span class="at">na.rm=</span><span class="cn">FALSE</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>precio_por_barrio <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(Precio <span class="sc">~</span>Barrio, airbnb_entire, <span class="at">FUN =</span>mean, <span class="at">na.rm=</span><span class="cn">FALSE</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a><span class="co">#print(precio_por_barrio)</span></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>precio_por_barrio<span class="ot">&lt;-</span><span class="fu">aggregate</span>(. <span class="sc">~</span> Barrio, airbnb_entire[<span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"Precio"</span>)], mean,<span class="at">na.rm=</span><span class="cn">TRUE</span>)</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(precio_por_barrio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 119   2</code></pre>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>precio_por_barrio<span class="ot">&lt;-</span>precio_por_barrio[<span class="fu">order</span>(precio_por_barrio<span class="sc">$</span>Precio,<span class="at">decreasing =</span> T),]</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(precio_por_barrio,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio   Precio
77       Palomas 309.7500
50 Fuentelareina 180.0000
93     Recoletos 161.9254
43    El Plantío 150.0000
30    Castellana 141.3889</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>barrios<span class="ot">&lt;-</span><span class="fu">head</span>(precio_por_barrio,<span class="dv">5</span>)<span class="sc">$</span>Barrio</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cuantos apartamentos hay en cada uno de esos barrios? Mostrar una dataframe con el nombre del barrio, el precio y el número de entradas. <strong>dataframen nuevo</strong></p>
<p>Ayuda: Podeis crear un nuevo dataframe con las columnas “Barrio” y “Freq” que contenga el número de entradas en cada barrio y hacer un merge con el dataframe del punto anterior.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Contar el número de apartamentos en cada barrio</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>count_value <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">table</span>(airbnb_entire<span class="sc">$</span>Barrio))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(count_value) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Barrio"</span>, <span class="st">"Freq"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinar el número de apartamentos con el precio medio por barrio</span></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>mean_price <span class="ot">&lt;-</span> <span class="fu">merge</span>(precio_por_barrio, count_value, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Ordenar en orden descendente según el precio medio</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>mean_price <span class="ot">&lt;-</span> mean_price[<span class="fu">order</span>(mean_price<span class="sc">$</span>Precio, <span class="at">decreasing =</span> <span class="cn">TRUE</span>), ]</span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los 5 barrios con los precios medios más altos y su número de entradas</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mean_price, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Barrio   Precio Freq
77       Palomas 309.7500    4
50 Fuentelareina 180.0000    2
93     Recoletos 161.9254  135
43    El Plantío 150.0000    1
30    Castellana 141.3889   73</code></pre>
</div>
</div>
<p>Partiendo del dataframe anterior, muestra los 5 barrios con mayor precio, pero que tengan más de 100 entradas de alquiler.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar los barrios con más de 100 entradas</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>barrios_filtrados <span class="ot">&lt;-</span> mean_price[mean_price<span class="sc">$</span>Freq <span class="sc">&gt;</span> <span class="dv">100</span>, ]</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los 5 barrios con los precios más altos entre los filtrados</span></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(barrios_filtrados, <span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Barrio    Precio Freq
93  Recoletos 161.92537  135
52       Goya 111.33803  142
106       Sol 100.75036  701
108 Trafalgar  98.57848  223
59   Justicia  98.25468  534</code></pre>
</div>
</div>
<p><strong>Dibuja</strong> el diagrama de densidad de distribución de los diferentes precios. Serían 5 gráficas, una por cada barrio. Clase 4 -&gt; funciones R</p>
<p>ggplot geom -density(()</p>
<p>grup by barrio, son 5 graficas una encima de la otra</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificar los 5 barrios con más de 100 entradas</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>barrios <span class="ot">&lt;-</span> <span class="fu">head</span>(<span class="fu">subset</span>(mean_price, mean_price<span class="sc">$</span>Freq <span class="sc">&gt;</span> <span class="dv">100</span>), <span class="dv">5</span>)<span class="sc">$</span>Barrio</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el dataframe original para incluir solo los 5 barrios seleccionados</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>subset_df <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">%in%</span> barrios)</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un gráfico de densidad separado para cada barrio</span></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> subset_df, <span class="fu">aes</span>(<span class="at">x =</span> Precio, <span class="at">color =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">bw =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Diagrama de Densidad de Precios por Barrio"</span>,</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Precio"</span>,</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Densidad"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="GabrielaCordova_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Calcula el tamaño medio, en metros cuadrados, para los 5 barrios anteriores y muestralo en el mismo dataframe junto con el precio y número de entradas</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el tamaño medio en metros cuadrados por barrio</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>mean_size <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(. <span class="sc">~</span> Barrio, <span class="at">data =</span> airbnb_entire[<span class="fu">c</span>(<span class="st">"Barrio"</span>,<span class="st">"MetrosCuadrados"</span>)], <span class="at">FUN =</span> mean, <span class="at">na.rm=</span>T)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Combinar los dataframes de tamaño medio, precio y número de entradas</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>result_df <span class="ot">&lt;-</span> <span class="fu">merge</span>(<span class="fu">subset</span>(mean_price, mean_price<span class="sc">$</span>Freq <span class="sc">&gt;</span> <span class="dv">100</span>), mean_size, <span class="at">by =</span> <span class="st">"Barrio"</span>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>result_df<span class="ot">&lt;-</span>result_df[<span class="fu">order</span>(result_df<span class="sc">$</span>Precio,<span class="at">decreasing =</span> T),]</span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(result_df,<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Barrio    Precio Freq MetrosCuadrados
8  Recoletos 161.92537  135        26.66316
4       Goya 111.33803  142        51.68504
9        Sol 100.75036  701        45.61692
10 Trafalgar  98.57848  223        29.30426
5   Justicia  98.25468  534        28.52669</code></pre>
</div>
</div>
<p>Dibuja el diagrama de <strong>densidad</strong> de distribución de los diferentes tamaños de apartamentos. Serían 5 gráficas, una por cada barrio. ggplot tamano medio ggplo gor densiry grup by barrio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>datos_top5<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio <span class="sc">%in%</span> barrios)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear las gráficas de densidad por barrio</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(datos_top5, <span class="fu">aes</span>(<span class="at">x =</span> MetrosCuadrados, <span class="at">color =</span> Barrio)) <span class="sc">+</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>)<span class="co"># +</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1645 rows containing non-finite values (`stat_density()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="GabrielaCordova_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta claro que las medias de metros cuadrados de cada uno de estos 5 barrios parecen ser diferentes, pero ¿son estadísticamente diferentes? ¿Que test habría que usar para comprobarlo? <strong>cuantos grupo, es gausiano, aov</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Selecciona los datos solo para los 5 barrios principales.</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>datos_top5<span class="ot">&lt;-</span><span class="fu">subset</span>(airbnb_entire,Barrio <span class="sc">%in%</span> barrios)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co">#para cada uno de estos 5 barrios, se calcula el precio medio de los metros cuadrados y se realiza una prueba de normalidad de Shapiro-Wilk para verificar si los datos siguen una distribución gaussiana.</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (barrio <span class="cf">in</span> <span class="fu">unique</span>(datos_top5<span class="sc">$</span>Barrio)){</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>    df<span class="ot">&lt;-</span>datos_top5[<span class="fu">which</span>(datos_top5<span class="sc">$</span>Barrio<span class="sc">==</span><span class="fu">as.character</span>(barrio)),]</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"Precio medio tipo"</span>,barrio,<span class="st">" = "</span>,<span class="fu">mean</span>(df<span class="sc">$</span>MetrosCuadrados,<span class="at">na.rm=</span>T)))</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">nrow</span>(df)<span class="sc">&gt;</span><span class="dv">5000</span>){</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>        df<span class="ot">&lt;-</span>df[<span class="dv">1</span><span class="sc">:</span><span class="dv">5000</span>,]</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>    sp<span class="ot">&lt;-</span><span class="fu">shapiro.test</span>(df<span class="sc">$</span>MetrosCuadrados)</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">" - Test shapiro pvalor = "</span>,sp<span class="sc">$</span>p.value))</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Precio medio tipo Sol  =  45.6169213833333"
[1] " - Test shapiro pvalor =  8.6913775134728e-07"
[1] "Precio medio tipo Justicia  =  28.5266858823529"
[1] " - Test shapiro pvalor =  0.00064192630271212"
[1] "Precio medio tipo Recoletos  =  26.663161"
[1] " - Test shapiro pvalor =  0"
[1] "Precio medio tipo Goya  =  51.6850356666667"
[1] " - Test shapiro pvalor =  0.519924091564745"
[1] "Precio medio tipo Trafalgar  =  29.3042605714286"
[1] " - Test shapiro pvalor =  0.0127581397426826"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co">#los datos no siguen una distribución gaussiana, para determinar si hay diferencias estadísticamente significativas entre los barrios en términos del tamaño de los apartamentos</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>kt<span class="ot">&lt;-</span><span class="fu">kruskal.test</span>(MetrosCuadrados<span class="sc">~</span>Barrio,datos_top5)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a><span class="co">#no hay evidencia suficiente para determinar que los tamaños de los apartamentos son diferentes en estos barrios</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>kt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Kruskal-Wallis rank sum test

data:  MetrosCuadrados by Barrio
Kruskal-Wallis chi-squared = 1.882, df = 4, p-value = 0.7574</code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"El pvalor del test es "</span>,kt<span class="sc">$</span>p.value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El pvalor del test es  0.757443581555649"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># la variabilidad observada en los tamaños de los apartamentos podría deberse al azar y no a diferencias reales entre los barrios.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para únicamente los pisos de alquiler en el barrio de Sol:</p>
<p><code>barrio_sol&lt;-subset(airbnb_entire,Barrio=="Sol")</code></p>
<p>Calcular un modelo lineal que combine alguna de estas variables: * NumBanyos * NumDormitorios * MaxOcupantes * MetrosCuadrados.</p>
<p>Primero calculamos la correlación para ver como se relacionan estas variables entre sí. <strong>corr</strong></p>
<p>Se observa que la correlación entre el número de dormitorios y los metros cuadrados es sorprendentemente baja. ¿Son de fiar esos números?</p>
<p>Mediante un histograma o curvas de densidad podemos descartar números que notienen sentido en el dataframe barrio_sol, para tener una matriz de correlación que tenga mayor sentido.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar el dataframe para el barrio de Sol</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>barrio_sol <span class="ot">&lt;-</span> <span class="fu">subset</span>(airbnb_entire, Barrio <span class="sc">==</span> <span class="st">"Sol"</span>)</span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Seleccionar las variables de interés</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>variables <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"NumBanyos"</span>, <span class="st">"NumDormitorios"</span>, <span class="st">"MaxOcupantes"</span>, <span class="st">"MetrosCuadrados"</span>)</span>
<span id="cb74-6"><a href="#cb74-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-7"><a href="#cb74-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación</span></span>
<span id="cb74-8"><a href="#cb74-8" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(barrio_sol[variables],<span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb74-9"><a href="#cb74-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-10"><a href="#cb74-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir la matriz de correlación</span></span>
<span id="cb74-11"><a href="#cb74-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(corr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.6761906    0.6578162       0.4820549
NumDormitorios  0.6761906      1.0000000    0.7594598       0.5684521
MaxOcupantes    0.6578162      0.7594598    1.0000000       0.4286233
MetrosCuadrados 0.4820549      0.5684521    0.4286233       1.0000000</code></pre>
</div>
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Explorar los datos con histogramas </span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))  <span class="co"># Crear un diseño de subgráficos 2x2</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (variable <span class="cf">in</span> variables) {</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hist</span>(barrio_sol[[variable]], <span class="at">main =</span> <span class="fu">paste</span>(<span class="st">"Histograma de"</span>, variable), <span class="at">xlab =</span> variable)</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="GabrielaCordova_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Restablecer el diseño de los gráficos</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Mirando el histograma de metros cuadrados empiezan desde 0 metros cuadrado, tal vez no se deberian tener en cuenta esos datos</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>barrio_sol<span class="ot">&lt;-</span><span class="fu">subset</span>(barrio_sol, MetrosCuadrados<span class="sc">&gt;</span><span class="dv">30</span>)</span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la matriz de correlación</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(barrio_sol[variables],<span class="at">use=</span><span class="st">"pairwise.complete.obs"</span>)</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(corr) <span class="co">#con el valor alto de 0.81 parece una mejor relacion</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                NumBanyos NumDormitorios MaxOcupantes MetrosCuadrados
NumBanyos       1.0000000      0.7219697    0.8636095       0.5993495
NumDormitorios  0.7219697      1.0000000    0.7874931       0.8320954
MaxOcupantes    0.8636095      0.7874931    1.0000000       0.6755066
MetrosCuadrados 0.5993495      0.8320954    0.6755066       1.0000000</code></pre>
</div>
</div>
<p>Una vez que hayamos filtrado los datos correspondientes calcular el valor o la combinación de valores que mejor nos permite obtener el precio de un inmueble.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal </span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>MetrosCuadrados)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-65.547 -23.537  -0.514  10.746 121.394 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      28.4792    14.8893   1.913   0.0654 .  
MetrosCuadrados   1.0006     0.1581   6.330 5.56e-07 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 40.44 on 30 degrees of freedom
Multiple R-squared:  0.5719,    Adjusted R-squared:  0.5576 
F-statistic: 40.07 on 1 and 30 DF,  p-value: 5.561e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal </span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>NumBanyos)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-94.133 -20.953  -8.703  11.797 159.332 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    35.74      17.89   1.997   0.0549 .  
NumBanyos      52.47      11.04   4.751  4.7e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 46.69 on 30 degrees of freedom
Multiple R-squared:  0.4294,    Adjusted R-squared:  0.4103 
F-statistic: 22.57 on 1 and 30 DF,  p-value: 4.702e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal </span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>NumDormitorios ) </span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumDormitorios, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-89.028 -14.615  -3.865  19.219  61.972 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      44.700      9.168   4.876 3.31e-05 ***
NumDormitorios   38.666      4.220   9.162 3.37e-10 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 31.71 on 30 degrees of freedom
Multiple R-squared:  0.7367,    Adjusted R-squared:  0.7279 
F-statistic: 83.94 on 1 and 30 DF,  p-value: 3.374e-10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal </span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>MaxOcupantes  )</span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MaxOcupantes, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-86.900 -18.666  -5.003  14.991 115.100 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    23.270     17.333   1.342     0.19    
MaxOcupantes   16.163      2.864   5.643 3.79e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 43.05 on 30 degrees of freedom
Multiple R-squared:  0.5149,    Adjusted R-squared:  0.4988 
F-statistic: 31.85 on 1 and 30 DF,  p-value: 3.794e-06</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal múltiple</span></span>
<span id="cb88-2"><a href="#cb88-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>MetrosCuadrados<span class="sc">+</span>NumBanyos)</span>
<span id="cb88-3"><a href="#cb88-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb88-4"><a href="#cb88-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb88-5"><a href="#cb88-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados + NumBanyos, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-79.671 -10.463   2.130   8.989 124.049 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      12.8512    15.6018   0.824 0.416833    
MetrosCuadrados   0.7506     0.1853   4.051 0.000349 ***
NumBanyos        25.2424    11.2131   2.251 0.032125 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 37.95 on 29 degrees of freedom
Multiple R-squared:  0.6356,    Adjusted R-squared:  0.6104 
F-statistic: 25.29 on 2 and 29 DF,  p-value: 4.403e-07</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal múltiple</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>MetrosCuadrados<span class="sc">+</span>NumDormitorios)</span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados + NumDormitorios, data = barrio_sol)

Residuals:
   Min     1Q Median     3Q    Max 
-87.11 -17.24  -2.55  20.46  66.59 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      38.5659    11.9692   3.222  0.00314 ** 
MetrosCuadrados   0.1807     0.2248   0.804  0.42799    
NumDormitorios   33.5454     7.6545   4.382  0.00014 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 31.9 on 29 degrees of freedom
Multiple R-squared:  0.7424,    Adjusted R-squared:  0.7247 
F-statistic:  41.8 on 2 and 29 DF,  p-value: 2.869e-09</code></pre>
</div>
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal múltiple</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>MetrosCuadrados<span class="sc">+</span>NumBanyos<span class="sc">+</span>NumDormitorios)</span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ MetrosCuadrados + NumBanyos + NumDormitorios, 
    data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-82.501 -14.173  -3.726  20.732  71.209 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      34.1280    14.6265   2.333  0.02704 * 
MetrosCuadrados   0.1812     0.2276   0.796  0.43271   
NumBanyos         5.9818    11.0408   0.542  0.59225   
NumDormitorios   31.1029     8.9654   3.469  0.00171 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 32.3 on 28 degrees of freedom
Multiple R-squared:  0.7451,    Adjusted R-squared:  0.7178 
F-statistic: 27.28 on 3 and 28 DF,  p-value: 1.848e-08</code></pre>
</div>
<div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un modelo de regresión lineal múltiple</span></span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol,<span class="at">formula=</span>Precio<span class="sc">~</span>NumBanyos<span class="sc">+</span>NumDormitorios<span class="sc">+</span>MetrosCuadrados<span class="sc">+</span>MaxOcupantes)</span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen del modelo</span></span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">summary</span>(modelo))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Precio ~ NumBanyos + NumDormitorios + MetrosCuadrados + 
    MaxOcupantes, data = barrio_sol)

Residuals:
    Min      1Q  Median      3Q     Max 
-78.882 -15.956  -2.229  20.098  68.919 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)      32.2483    15.6064   2.066  0.04851 * 
NumBanyos         1.7501    15.5585   0.112  0.91127   
NumDormitorios   30.0010     9.5275   3.149  0.00398 **
MetrosCuadrados   0.1734     0.2320   0.748  0.46122   
MaxOcupantes      1.9309     4.9223   0.392  0.69793   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 32.8 on 27 degrees of freedom
Multiple R-squared:  0.7466,    Adjusted R-squared:  0.709 
F-statistic: 19.88 on 4 and 27 DF,  p-value: 9.928e-08</code></pre>
</div>
</div>
<p>¿Que variable es más fiable para conocer el precio de un inmueble, el número de habitaciones o los metros cuadrados? <strong>pvalor mas estrellitas p valor bajo</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="co"># parece que el número de dormitorios (NumDormitorios) es más confiable para predecir el precio de un inmueble en el barrio de Sol, ya que es un predictor significativo en todos los modelos y tiene un mayor impacto en el precio en comparación con los metros cuadrados.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada metro cuadrado extra del piso? <strong>precio en funcion de metros cuadrado -&gt; confint(lm(precio-metro2,df))</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo de regresión lineal simple</span></span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol, <span class="at">formula=</span>Precio <span class="sc">~</span> MetrosCuadrados)</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza del 95% para el coeficiente de MetrosCuadrados</span></span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelo)</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el intervalo de confianza</span></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a>intervalo_confianza</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     2.5 %    97.5 %
(Intercept)     -1.9286895 58.887121
MetrosCuadrados  0.6777739  1.323401</code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="co">#los metros cuadrados tienen un efecto significativo en el precio del alquiler en el conjunto de datos y se espera un aumento significativo en el precio por cada metro cuadrado adicional del piso</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Responde con su correspondiente margen de error del 95%, ¿cuantos euros incrementa el precio del alquiler por cada habitación?</p>
<p><strong>confint(lm(precio-habitacion,df))</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar el modelo de regresión lineal simple</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(barrio_sol, <span class="at">formula=</span>Precio <span class="sc">~</span> NumDormitorios)</span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-4"><a href="#cb100-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza del 95% para el coeficiente de NumDormitorios</span></span>
<span id="cb100-5"><a href="#cb100-5" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">confint</span>(modelo)</span>
<span id="cb100-6"><a href="#cb100-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb100-7"><a href="#cb100-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el intervalo de confianza</span></span>
<span id="cb100-8"><a href="#cb100-8" aria-hidden="true" tabindex="-1"></a>intervalo_confianza</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  2.5 %  97.5 %
(Intercept)    25.97660 63.4224
NumDormitorios 30.04669 47.2848</code></pre>
</div>
<div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co">#el número de dormitorios tiene un efecto significativo en el precio del alquiler en el conjunto de datos y se espera un aumento significativo en el precio por cada dormitorio adicional en el piso</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>¿Cual es la probabilidad de encontrar, en el barrio de Sol, un apartamento en alquiler con 3 dormitorios? ¿Cual es el intervalo de confianza de esa probabilidad?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular la probabilidad directamente</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a>probabilidad <span class="ot">&lt;-</span> <span class="fu">sum</span>(barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">==</span> <span class="dv">3</span>) <span class="sc">/</span> <span class="fu">nrow</span>(barrio_sol)</span>
<span id="cb103-3"><a href="#cb103-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-4"><a href="#cb103-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el intervalo de confianza usando binom.test</span></span>
<span id="cb103-5"><a href="#cb103-5" aria-hidden="true" tabindex="-1"></a>intervalo_confianza <span class="ot">&lt;-</span> <span class="fu">binom.test</span>(<span class="fu">sum</span>(barrio_sol<span class="sc">$</span>NumDormitorios <span class="sc">==</span> <span class="dv">3</span>), <span class="fu">nrow</span>(barrio_sol))<span class="sc">$</span>conf.int</span>
<span id="cb103-6"><a href="#cb103-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb103-7"><a href="#cb103-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar la probabilidad y el intervalo de confianza</span></span>
<span id="cb103-8"><a href="#cb103-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">"La probabilidad es:"</span>, probabilidad))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "La probabilidad es: 0.09375"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"El margen de confianza es:"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "El margen de confianza es:"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(intervalo_confianza)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01976718 0.25022695
attr(,"conf.level")
[1] 0.95</code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co">#la probabilidad de encontrar un apartamento en alquiler con 3 dormitorios en el barrio de Sol es del 10.71%.</span></span>
<span id="cb109-2"><a href="#cb109-2" aria-hidden="true" tabindex="-1"></a><span class="co">#la confianza del 95%, podemos encontrar un apartamento con 3 dormitorios en el barrio de Sol  dentro de este intervalo(2.27%) hasta (28.23%).</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>